[package]
name = "kern-semantic"
version = "0.1.0"
edition = "2021"

[lib]
name = "kern_semantic"
path = "lib.rs"

[dependencies]
kern_parser = { path = "../kern-parser" }
kern_graph_builder = { path = "../kern-graph-builder" }

[dev-dependencies]