[package]
name = "kern_bytecode"
version = "0.1.0"
edition = "2021"

[dependencies]
kern-ast = { path = "../kern-ast" }
kern-parser = { path = "../kern-parser" }
kern-lexer = { path = "../kern-lexer" }
kern-graph-builder = { path = "../kern-graph-builder" }

[dev-dependencies]